version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - wfxr
  labels:
  - dependencies
  commit-message:
    prefix: "chore"
    prefix-development: "chore"
    include: "scope"
