[package]
name = "grm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
curl = "0.4.46"
flate2 = "1.0.31"
futures-util = "0.3.30"
indicatif = "0.17.8"
infer = "0.16.0"
octocrab = "0.39"
once_cell = "1.19.0"
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["stream"] }
serde = { version = "1", features = ["derive"] }
tar = "0.4.41"
tempfile = "3.11.0"
tokio = { version = "1.39", features = ["full"] }
toml = "0.8"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = "2.5.0"
yansi = "1.0.1"
zip = "2.1.6"
clap_complete = { version = "4" }
home = "0.5.9"
constcat = "0.5.0"
thiserror = "1.0.63"
indexmap = { version = "2.3", features = ["rayon", "serde"] }
url = "2.5.2"
regex-macro = "0.2.0"
itertools = "0.13.0"
rayon = "1.10.0"
maplit = "1.0.2"
globwalk = "0.9.1"
upon = "0.8.1"
pretty_assertions = "1.4.0"
goldie = "0.5.0"
futures = "0.3.30"
sha256 = "1.5.0"
xdg = "2.5.2"
toml_edit = "0.22.20"
nucleo = "0.5.0"
skim = "0.10.4"

[dependencies.clap]
version = "4"
default-features = false
features = [
    "std",
    "help",
    "usage",
    "error-context",
    "suggestions",   # default excluding "color"
    "cargo",
    "env",
    "derive",        # optional
]

[build-dependencies]
anyhow = "1"
